#!/bin/zsh

#bindkey -e

zstyle :compinstall filename '/home/rockdon/.zshrc'

autoload -U compinit
autoload -U colors
compinit
colors

HISTFILE=~/.histfile
HISTSIZE=1000000000
SAVEHIST=1000000000
setopt APPEND_HISTORY

# The following stanza configures the shell to be green for 
#   normal users and red for root. This uses standard ANSI shell
#   escapes for colors, feel free to change to your liking.
if [[ $USER != 'root' ]] ; then
    c1="%{$fg_no_bold[green]%}" # base color1
    c2="%{$fg_bold[green]%}"    # base color2
    c3="%{$fg_bold[black]%}"   # punctuation
else
    c1="%{$fg_no_bold[red]%}" # base color1
    c2="%{$fg_bold[red]%}"    # base color2
    c3="%{$fg_bold[black]%}"  # punctuation
fi

# The following stanza configures the hostname to be green for 
#   the local hostname, and red for anything else. This is meant to 
#   keep even tired users aware that they may be issuing commands
#   on machines that are not localhost
if [[ $HOST != 'icarus.local' ]] ; then
    h1="%{$fg_bold[red]%}"
else
    h1="%{$fg_no_bold[white]%}"
fi

PROMPT="$c2($c1%n$c3@$h1%m$c2)"$c2($c3: $c1%~$c2 )$'\n'
PROMPT+="$c1%# %{$reset_color%}"
#RPROMPT="$c2($c1%D{%H:%M}$c3+$c1%D{%d%b%y}$c2)%{$reset_color%}"

setopt extendedglob
setopt autocd
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt autopushd pushdminus pushdsilent pushdtohome
setopt PUSHD_IGNORE_DUPS
setopt correctall

source ~/.zsh_shellvars
source ~/.zsh_aliases
source ~/.zsh_functions
#source /sw/bin/init.sh

#cdpath=(~ ..) ## on cd command offer dirs in home and one dir up.

if [ -d ~/bin ]; then
    PATH="${PATH}":~/bin
fi
 
if [ -d ~/bin/rbin ]; then
    PATH="${PATH}":~/bin/rbin
fi

if [ -d ~/bin/pbin ]; then
    PATH="${PATH}":~/bin/pbin
fi

if [ -d ~/bin/shbin ]; then
    PATH="${PATH}":~/bin/shbin
fi

if [ -d /opt/local/bin ]; then
    PATH="${PATH}":/opt/local/bin:
fi

if [ -d /opt/local/sbin ]; then
    PATH="${PATH}":/opt/local/sbin
fi

#if [ -d /opt/local/share/java/jruby/bin ]; then
#    PATH="${PATH}":/opt/local/share/java/jruby/bin
#fi

# taking the plunge
set -o vi

bindkey '^G' push-line

[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"  # This loads RVM into a shell session.


